Add default environment variables for Heroku deployment
To prevent errors on first start like this:

    [log][trackers] register tracker foursquare
    [log][trackers] register tracker twitter
    [log][trackers] register tracker github
    [log][trackers] register tracker runkeeper
    [log][trackers] register tracker fitbit
    [log][api] register api auth
    [log][api] register api data
    [log][api] register api models
    [log][api] register api events
    [log][api] register api trackers
    [log][trackers] init tracker chrome
    [log][api] start api server
    [log][notifications] start socket.io server
    [log][trackers] Initialize 7 trackers
    [log][trackers] init tracker foursquare
    [error][trackers] github  tracker need oauth 'clientId' and 'clientSecret' to work
    [error][trackers] foursquare  tracker need oauth 'clientId' and 'clientSecret'
    [log][trackers] init tracker twitter
    [error][trackers] twitter  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][trackers] init tracker github
    [error][trackers] facebook  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][trackers] init tracker facebook
    [log][trackers] Initialize 7 trackers
    [log][trackers] init tracker fitbit
    [error][trackers] fitbit  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][web] Server is listening on port 40097
    [log][trackers] init tracker runkeeper
    [error][trackers] runkeeper  tracker need oauth 'clientId' and 'clientSecret' to work
    Error in the application:
    Error: Configuration Error: Client information not supplied.
        at configure (/app/node_modules/node-foursquare/lib/node-foursquare.js:45:13)
    [log][tasks] add task task1
    [log][trackers] init tracker chrome
    [log][trackers] init tracker facebook
    [log][trackers] init tracker foursquare
        at TrackerService.init (/app/lib/trackers/main.js:73:10)
        at start (/app/lib/trackers/main.js:167:12)
        at Function._.each._.forEach (/app/node_modules/underscore/underscore.js:86:24)
        at setup (/app/lib/worker.main/main.js:8:14)
        at Plugin.load (/app/node_modules/engineer/lib/plugin.js:47:21)
        at Application.load.Q.fbind._.reduce.d.then.then.that.plugins.(anonymous function) (/app/node_modules/engineer/lib/application.js:45:31)
        at module.exports (/app/node_modules/node-foursquare/lib/node-foursquare.js:67:12)
        at trackers.register.initWorker (/app/lib/tracker.foursquare/main.js:27:22)
        at Object.start (/app/lib/trackers/main.js:163:5)
    State changed from starting to crashed
    Process exited with status 1
    State changed from crashed to starting
    Starting process with command `node bin/reportr.js run --mode=all`
    [log][database] Connection to mongodb://heroku_app123456789:123456@ds053428.mongolab.com:53428/heroku_app123456789 ...
    [log][database] Open on mongodb://heroku_app123456789:123456@ds053428.mongolab.com:53428/heroku_app123456789
    [log][queue] start queue
    [log][trackers] register tracker chrome
    [log][trackers] register tracker facebook
    [log][trackers] register tracker foursquare
    [log][trackers] register tracker twitter
    [log][trackers] register tracker github
    [log][trackers] register tracker runkeeper
    [log][trackers] register tracker fitbit
    [log][api] register api auth
    [log][api] register api data
    [log][api] register api models
    [log][api] register api events
    [log][api] register api trackers
    [log][api] start api server
    [log][notifications] start socket.io server
    [log][trackers] init tracker foursquare
    [log][trackers] Initialize 7 trackers
    [log][trackers] init tracker chrome
    [log][trackers] init tracker twitter
    [log][trackers] init tracker facebook
    [error][trackers] facebook  tracker need oauth 'clientId' and 'clientSecret' to work
    [error][trackers] foursquare  tracker need oauth 'clientId' and 'clientSecret' to work
    [error][trackers] twitter  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][trackers] init tracker github
    [error][trackers] github  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][trackers] init tracker fitbit
    [error][trackers] fitbit  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][trackers] init tracker runkeeper
    [log][trackers] Initialize 7 trackers
    [error][trackers] runkeeper  tracker need oauth 'clientId' and 'clientSecret' to work
    [log][web] Server is listening on port 38774
    [log][trackers] init tracker chrome
    [log][tasks] add task task1
    [log][trackers] init tracker foursquare
    Error: Configuration Error: Client information not supplied.
    [log][trackers] init tracker facebook
        at module.exports (/app/node_modules/node-foursquare/lib/node-foursquare.js:67:12)
        at trackers.register.initWorker (/app/lib/tracker.foursquare/main.js:27:22)
    Error in the application:
        at TrackerService.init (/app/lib/trackers/main.js:73:10)
        at Function._.each._.forEach (/app/node_modules/underscore/underscore.js:86:24)
        at start (/app/lib/trackers/main.js:167:12)
        at setup (/app/lib/worker.main/main.js:8:14)
        at Plugin.load (/app/node_modules/engineer/lib/plugin.js:47:21)
        at configure (/app/node_modules/node-foursquare/lib/node-foursquare.js:45:13)
        at Object.start (/app/lib/trackers/main.js:163:5)
        at Application.load.Q.fbind._.reduce.d.then.then.that.plugins.(anonymous function) (/app/node_modules/engineer/lib/application.js:45:31)
    State changed from up to crashed
    Process exited with status 1